# TODO Documentation

drubo:
  commands:
    'site:reinstall': { disabled: true }

drupal:
  account:
    mail: 'admin@example.com'
    name: 'admin'
    pass: ~
  site:
    language: 'en'
    mail: 'admin@example.com'
    name: 'Drupal'
    profile: 'standard'

drupalconsole:
  ansi: true
  path: 'bin/drupal'

drush:
  path: 'bin/drush'

filesystem:
  directories:
    config:
      path: '.drupal/config'
    docroot:
      path: 'docroot'
