# TODO Documentation

account:
  mail: 'admin@example.com'
  name: 'admin'
  pass: null

site:
  language: 'en'
  mail: 'admin@example.com'
  name: 'Drupal'
  profile: 'standard'

docroot:
  path: 'docroot'

drupalconsole:
  ansi: true
  path: 'bin/drupal'

drush:
  path: 'bin/drush'

commands:
  'site:reinstall': { disabled: true }
